Firmware SDK: bc_ls013b7dh03
bc_ls013b7dh03
Driver for LS013B7DH03 1.28" HR-TFT Memory LCD.
Data Structures
struct bc_ls013b7dh03_t
Instance.
Macros
#define BC_LS013B7DH03_FRAMEBUFFER_SIZE (1 + ((1+16+1) * 128) + 1)
#define BC_LS013B7DH03_WIDTH 128
#define BC_LS013B7DH03_HEIGHT 128
Functions
void bc_ls013b7dh03_init (bc_ls013b7dh03_t *self, bool(*pin_cs_set)(bool state))
Initialize lcd driver.
bc_gfx_caps_t bc_ls013b7dh03_get_caps (bc_ls013b7dh03_t *self)
Get capabilities.
bool bc_ls013b7dh03_is_ready (bc_ls013b7dh03_t *self)
Check if lcd is ready for commands.
void bc_ls013b7dh03_clear (bc_ls013b7dh03_t *self)
Clear.
void bc_ls013b7dh03_draw_pixel (bc_ls013b7dh03_t *self, int x, int y, uint32_t color)
Lcd draw pixel.
uint32_t bc_ls013b7dh03_get_pixel (bc_ls013b7dh03_t *self, int x, int y)
Lcd get pixel.
bool bc_ls013b7dh03_update (bc_ls013b7dh03_t *self)
Lcd update, send data.
bool bc_ls013b7dh03_clear_memory_command (bc_ls013b7dh03_t *self)
Send Lcd clear memory command.
const bc_gfx_driver_t * bc_ls013b7dh03_get_driver (void)
Get Lcd driver.
Detailed Description
Driver for LS013B7DH03 1.28" HR-TFT Memory LCD.
Function Documentation
void bc_ls013b7dh03_clear (bc_ls013b7dh03_t * self)
Clear.
Parameters
[in] self Instance
Definition at line 50 of file bc_ls013b7dh03.c.
Referenced by bc_ls013b7dh03_get_driver().
bool bc_ls013b7dh03_clear_memory_command (bc_ls013b7dh03_t * self)
Send Lcd clear memory command.
Returns
true On success
false On failure
Definition at line 149 of file bc_ls013b7dh03.c.
void bc_ls013b7dh03_draw_pixel (bc_ls013b7dh03_t * self, int x, int y, uint32_t color)
Lcd draw pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color Pixels state
Definition at line 64 of file bc_ls013b7dh03.c.
Referenced by bc_ls013b7dh03_get_driver().
bc_gfx_caps_t bc_ls013b7dh03_get_caps (bc_ls013b7dh03_t * self)
Get capabilities.
Parameters
[in] self Instance
Definition at line 34 of file bc_ls013b7dh03.c.
Referenced by bc_ls013b7dh03_get_driver().
uint32_t bc_ls013b7dh03_get_pixel (bc_ls013b7dh03_t * self, int x, int y)
Lcd get pixel.
Parameters
[in] self Instance
[in] left Pixels from left edge
[in] top Pixels from top edge
[in] color Pixels state
Definition at line 85 of file bc_ls013b7dh03.c.
Referenced by bc_ls013b7dh03_get_driver().
void bc_ls013b7dh03_init (bc_ls013b7dh03_t * self, bool(*)(bool state) pin_cs_set)
Initialize lcd driver.
Parameters
[in] self Instance
Definition at line 11 of file bc_ls013b7dh03.c.
Referenced by bc_module_lcd_init().
bool bc_ls013b7dh03_is_ready (bc_ls013b7dh03_t * self)
Check if lcd is ready for commands.
Parameters
[in] self Instance
Returns
true If ready
false If not ready
Definition at line 43 of file bc_ls013b7dh03.c.
Referenced by bc_ls013b7dh03_get_driver().
bool bc_ls013b7dh03_update (bc_ls013b7dh03_t * self)
Lcd update, send data.
Parameters
[in] self Instance
Returns
true On success
false On failure
Definition at line 106 of file bc_ls013b7dh03.c.
Referenced by bc_ls013b7dh03_get_driver().