Firmware SDK: bc_sgp30
bc_sgp30
Driver for SGP30 VOC gas sensor.
Typedefs
typedef struct bc_sgp30_t bc_sgp30_t
SGP30 instance.
Enumerations
enum bc_sgp30_event_t {
BC_SGP30_EVENT_ERROR = 0,
BC_SGP30_EVENT_UPDATE = 1
}
Callback events.
Functions
void bc_sgp30_init (bc_sgp30_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SGP30.
void bc_sgp30_set_event_handler (bc_sgp30_t *self, void(*event_handler)(bc_sgp30_t *, bc_sgp30_event_t, void *), void *event_param)
Set callback function.
void bc_sgp30_set_update_interval (bc_sgp30_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_sgp30_measure (bc_sgp30_t *self)
Start measurement manually.
bool bc_sgp30_get_co2eq_ppm (bc_sgp30_t *self, uint16_t *ppm)
Get measured CO2eq in ppm (parts per million)
bool bc_sgp30_get_tvoc_ppb (bc_sgp30_t *self, uint16_t *ppb)
Get measured TVOC in ppb (parts per billion)
float bc_sgp30_set_compensation (bc_sgp30_t *self, float *t_celsius, float *rh_percentage)
Set sensor compensation (absolute humidity is calculated from temperature and relative humidity)
Detailed Description
Driver for SGP30 VOC gas sensor.
Enumeration Type Documentation
enum bc_sgp30_event_t
Callback events.
Enumerator
BC_SGP30_EVENT_ERROR
Error event.
BC_SGP30_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_sgp30.h.
Function Documentation
bool bc_sgp30_get_co2eq_ppm (bc_sgp30_t * self, uint16_t * ppm)
Get measured CO2eq in ppm (parts per million)
Parameters
[in] self Instance
[out] ppm Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 73 of file bc_sgp30.c.
Referenced by bc_tag_voc_get_co2eq_ppm().
bool bc_sgp30_get_tvoc_ppb (bc_sgp30_t * self, uint16_t * ppb)
Get measured TVOC in ppb (parts per billion)
Parameters
[in] self Instance
[out] ppb Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 85 of file bc_sgp30.c.
Referenced by bc_tag_voc_get_tvoc_ppb().
void bc_sgp30_init (bc_sgp30_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SGP30.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 17 of file bc_sgp30.c.
Referenced by bc_tag_voc_init().
bool bc_sgp30_measure (bc_sgp30_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 54 of file bc_sgp30.c.
Referenced by bc_sgp30_set_update_interval(), and bc_tag_voc_measure().
float bc_sgp30_set_compensation (bc_sgp30_t * self, float * t_celsius, float * rh_percentage)
Set sensor compensation (absolute humidity is calculated from temperature and relative humidity)
Parameters
[in] self Instance
[in] t_celsius Pointer to variable holding temperature in degrees of celsius (must be NULL if not available)
[in] rh_percentage Pointer to variable holding relative humidity in percentage (must be NULL if not available)
Returns
Absolute humidity in grams per cubic meter
Definition at line 97 of file bc_sgp30.c.
Referenced by bc_tag_voc_set_compensation().
void bc_sgp30_set_event_handler (bc_sgp30_t * self, void(*)(bc_sgp30_t *, bc_sgp30_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 32 of file bc_sgp30.c.
Referenced by bc_tag_voc_set_event_handler().
void bc_sgp30_set_update_interval (bc_sgp30_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 38 of file bc_sgp30.c.
Referenced by bc_tag_voc_set_update_interval().