Firmware SDK: bc_sht20
bc_sht20
Driver for SHT20 humidity sensor.
Typedefs
typedef struct bc_sht20_t bc_sht20_t
SHT20 instance.
Enumerations
enum bc_sht20_event_t {
BC_SHT20_EVENT_ERROR = 0,
BC_SHT20_EVENT_UPDATE = 1
}
Callback events.
Functions
void bc_sht20_init (bc_sht20_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SHT20.
void bc_sht20_deinit (bc_sht20_t *self)
Deinitialize SHT20.
void bc_sht20_set_event_handler (bc_sht20_t *self, void(*event_handler)(bc_sht20_t *, bc_sht20_event_t, void *), void *event_param)
Set callback function.
void bc_sht20_set_update_interval (bc_sht20_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_sht20_measure (bc_sht20_t *self)
Start measurement manually.
bool bc_sht20_get_humidity_raw (bc_sht20_t *self, uint16_t *raw)
Get measured humidity as raw value.
bool bc_sht20_get_humidity_percentage (bc_sht20_t *self, float *percentage)
Get measured humidity as percentage.
bool bc_sht20_get_temperature_raw (bc_sht20_t *self, uint16_t *raw)
Get measured temperature as raw value.
bool bc_sht20_get_temperature_celsius (bc_sht20_t *self, float *celsius)
Get measured temperature in degrees of Celsius.
bool bc_sht20_get_temperature_fahrenheit (bc_sht20_t *self, float *fahrenheit)
Get measured temperature in degrees of Fahrenheit.
bool bc_sht20_get_temperature_kelvin (bc_sht20_t *self, float *kelvin)
Get measured temperature in kelvin.
Detailed Description
Driver for SHT20 humidity sensor.
Enumeration Type Documentation
enum bc_sht20_event_t
Callback events.
Enumerator
BC_SHT20_EVENT_ERROR
Error event.
BC_SHT20_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_sht20.h.
Function Documentation
void bc_sht20_deinit (bc_sht20_t * self)
Deinitialize SHT20.
Parameters
[in] self Instance
Definition at line 31 of file bc_sht20.c.
bool bc_sht20_get_humidity_percentage (bc_sht20_t * self, float * percentage)
Get measured humidity as percentage.
Parameters
[in] self Instance
[in] percentage Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 86 of file bc_sht20.c.
Referenced by bc_module_climate_get_humidity_percentage(), and bc_tag_humidity_get_humidity_percentage().
bool bc_sht20_get_humidity_raw (bc_sht20_t * self, uint16_t * raw)
Get measured humidity as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 74 of file bc_sht20.c.
Referenced by bc_sht20_get_humidity_percentage(), and bc_tag_humidity_get_humidity_raw().
bool bc_sht20_get_temperature_celsius (bc_sht20_t * self, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] celsius Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 121 of file bc_sht20.c.
Referenced by bc_sht20_get_temperature_fahrenheit(), bc_sht20_get_temperature_kelvin(), and bc_tag_humidity_get_temperature_celsius().
bool bc_sht20_get_temperature_fahrenheit (bc_sht20_t * self, float * fahrenheit)
Get measured temperature in degrees of Fahrenheit.
Parameters
[in] self Instance
[out] fahrenheit Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 135 of file bc_sht20.c.
bool bc_sht20_get_temperature_kelvin (bc_sht20_t * self, float * kelvin)
Get measured temperature in kelvin.
Parameters
[in] self Instance
[out] kelvin Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 149 of file bc_sht20.c.
bool bc_sht20_get_temperature_raw (bc_sht20_t * self, uint16_t * raw)
Get measured temperature as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 109 of file bc_sht20.c.
Referenced by bc_sht20_get_temperature_celsius(), and bc_tag_humidity_get_temperature_raw().
void bc_sht20_init (bc_sht20_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SHT20.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 16 of file bc_sht20.c.
Referenced by bc_module_climate_init(), and bc_tag_humidity_init().
bool bc_sht20_measure (bc_sht20_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 60 of file bc_sht20.c.
Referenced by bc_module_climate_measure_all_sensors(), bc_module_climate_measure_hygrometer(), bc_sht20_set_update_interval(), and bc_tag_humidity_measure().
void bc_sht20_set_event_handler (bc_sht20_t * self, void(*)(bc_sht20_t *, bc_sht20_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 38 of file bc_sht20.c.
Referenced by bc_module_climate_init(), and bc_tag_humidity_init().
void bc_sht20_set_update_interval (bc_sht20_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 44 of file bc_sht20.c.
Referenced by bc_module_climate_set_update_interval_all_sensors(), bc_module_climate_set_update_interval_hygrometer(), and bc_tag_humidity_set_update_interval().