Firmware SDK: bc_onewire
bc_onewire
Driver for 1-Wire.
Macros
#define BC_ONEWIRE_DEVICE_NUMBER_SKIP_ROM 0
Functions
void bc_onewire_init (bc_gpio_channel_t channel)
Initialize 1-Wire.
bool bc_onewire_transaction_start (bc_gpio_channel_t channel)
Start transaction, enable pll and run timer.
bool bc_onewire_transaction_stop (bc_gpio_channel_t channel)
Stop transaction.
bool bc_onewire_reset (bc_gpio_channel_t channel)
Reset the 1-Wire bus and return the presence of any device.
void bc_onewire_select (bc_gpio_channel_t channel, uint64_t *device_number)
Select device.
void bc_onewire_skip_rom (bc_gpio_channel_t channel)
Skip ROM.
void bc_onewire_write (bc_gpio_channel_t channel, const void *buffer, size_t length)
Select device.
void bc_onewire_read (bc_gpio_channel_t channel, void *buffer, size_t length)
Select device.
void bc_onewire_write_8b (bc_gpio_channel_t channel, uint8_t data)
Select device.
uint8_t bc_onewire_read_8b (bc_gpio_channel_t channel)
Select device.
void bc_onewire_write_bit (bc_gpio_channel_t channel, int bit)
Select device.
int bc_onewire_read_bit (bc_gpio_channel_t channel)
Select device.
int bc_onewire_search_all (bc_gpio_channel_t channel, uint64_t *device_list, size_t device_list_size)
Search for all devices on 1-Wire.
int bc_onewire_search_family (bc_gpio_channel_t channel, uint8_t family_code, uint64_t *device_list, size_t device_list_size)
Search for all devices on 1-Wire with family code.
void bc_onewire_search_start (uint8_t family_code)
Start of manual search, see also bc_onewire_search_next.
bool bc_onewire_search_next (bc_gpio_channel_t channel, uint64_t *device_number)
Manual search of next device.
void bc_onewire_auto_ds28e17_sleep_mode (bool on)
Enable call sleep mode for all ds28e17 after transaction.
uint8_t bc_onewire_crc8 (const void *buffer, size_t length, uint8_t crc)
Calculate 8-bit CRC.
uint16_t bc_onewire_crc16 (const void *buffer, size_t length, uint16_t crc)
Calculate 16-bit CRC, polynomial 0x8005.
Detailed Description
Driver for 1-Wire.
Function Documentation
void bc_onewire_auto_ds28e17_sleep_mode (bool on)
Enable call sleep mode for all ds28e17 after transaction.
Parameters
[in] on
Definition at line 562 of file bc_onewire.c.
Referenced by bc_ds28e17_init(), and bc_soil_sensor_init_multiple().
uint16_t bc_onewire_crc16 (const void * buffer, size_t length, uint16_t crc)
Calculate 16-bit CRC, polynomial 0x8005.
Parameters
[in] buffer
[in] length Number of bytes
[in] The crc starting value
Returns
Calculated CRC
Definition at line 224 of file bc_onewire.c.
uint8_t bc_onewire_crc8 (const void * buffer, size_t length, uint8_t crc)
Calculate 8-bit CRC.
Parameters
[in] buffer
[in] length Number of bytes
[in] The crc starting value
Returns
Calculated CRC
Definition at line 197 of file bc_onewire.c.
Referenced by bc_onewire_search_next().
void bc_onewire_init (bc_gpio_channel_t channel)
Initialize 1-Wire.
Parameters
channel GPIO channel
Definition at line 35 of file bc_onewire.c.
Referenced by bc_ds28e17_init(), bc_module_sensor_onewire_init(), bc_onewire_relay_init(), and bc_soil_sensor_init_multiple().
void bc_onewire_read (bc_gpio_channel_t channel, void * buffer, size_t length)
Select device.
Parameters
channel GPIO channel
[out] data Output which have been read
[in] length Number of bytes to be read
Definition at line 142 of file bc_onewire.c.
uint8_t bc_onewire_read_8b (bc_gpio_channel_t channel)
Select device.
Parameters
channel GPIO channel
Returns
data which have been read
Definition at line 159 of file bc_onewire.c.
Referenced by bc_onewire_relay_set_state().
int bc_onewire_read_bit (bc_gpio_channel_t channel)
Select device.
Parameters
channel GPIO channel
Returns
bit which have been read
Definition at line 174 of file bc_onewire.c.
bool bc_onewire_reset (bc_gpio_channel_t channel)
Reset the 1-Wire bus and return the presence of any device.
Parameters
channel GPIO channel
Returns
true Device present
false No device present
Definition at line 91 of file bc_onewire.c.
Referenced by bc_ds28e17_set_speed(), and bc_onewire_relay_set_state().
int bc_onewire_search_all (bc_gpio_channel_t channel, uint64_t * device_list, size_t device_list_size)
Search for all devices on 1-Wire.
Parameters
[in] channel GPIO channel
[out] device_list Pointer to destination array holding list of devices
[in] device_list_size Size of array holding list of devices
Returns
Number of found devices
Definition at line 182 of file bc_onewire.c.
int bc_onewire_search_family (bc_gpio_channel_t channel, uint8_t family_code, uint64_t * device_list, size_t device_list_size)
Search for all devices on 1-Wire with family code.
Parameters
[in] channel GPIO channel
[in] family_code
[out] device_list Pointer to destination array holding list of devices
[in] device_list_size Size of array holding list of devices
Returns
Number of found devices
Definition at line 189 of file bc_onewire.c.
bool bc_onewire_search_next (bc_gpio_channel_t channel, uint64_t * device_number)
Manual search of next device.
Parameters
[in] device_number GPIO channel
[in] device_number 64b device number
Returns
true if new device was found, false if ther are no more devices on the bus
Definition at line 425 of file bc_onewire.c.
void bc_onewire_search_start (uint8_t family_code)
Start of manual search, see also bc_onewire_search_next.
Parameters
[in] family_code Family code of 1-Wire device or NULL
Definition at line 413 of file bc_onewire.c.
void bc_onewire_select (bc_gpio_channel_t channel, uint64_t * device_number)
Select device.
Parameters
channel GPIO channel
[in] device_number Device number (for 0 skip ROM)
Definition at line 104 of file bc_onewire.c.
Referenced by bc_ds28e17_set_speed(), and bc_onewire_relay_set_state().
void bc_onewire_skip_rom (bc_gpio_channel_t channel)
Skip ROM.
Parameters
channel GPIO channel
Definition at line 125 of file bc_onewire.c.
bool bc_onewire_transaction_start (bc_gpio_channel_t channel)
Start transaction, enable pll and run timer.
Parameters
channel GPIO channel
Returns
true On success
false On failure
Definition at line 51 of file bc_onewire.c.
Referenced by bc_ds28e17_set_speed().
bool bc_onewire_transaction_stop (bc_gpio_channel_t channel)
Stop transaction.
Parameters
channel GPIO channel
Returns
true On success
false On failure
Definition at line 67 of file bc_onewire.c.
Referenced by bc_ds28e17_set_speed().
void bc_onewire_write (bc_gpio_channel_t channel, const void * buffer, size_t length)
Select device.
Parameters
channel GPIO channel
[in] data Input data to be written
[in] length Number of bytes to be written
Definition at line 132 of file bc_onewire.c.
Referenced by bc_ds28e17_set_speed(), and bc_onewire_relay_set_state().
void bc_onewire_write_8b (bc_gpio_channel_t channel, uint8_t data)
Select device.
Parameters
channel GPIO channel
[in] data Input data to be written
Definition at line 152 of file bc_onewire.c.
void bc_onewire_write_bit (bc_gpio_channel_t channel, int bit)
Select device.
Parameters
channel GPIO channel
[in] bit Input bit to be written
Definition at line 167 of file bc_onewire.c.