Firmware SDK: bc_atsha204
bc_atsha204
Driver for Atmel ATSHA204 CryptoAuthentication.
Typedefs
typedef struct bc_atsha204_t bc_atsha204_t
ATSHA204 instance.
Enumerations
enum bc_atsha204_event_t {
BC_ATSHA204_EVENT_ERROR = 0,
BC_ATSHA204_EVENT_REVISION_NUMBER = 1,
BC_ATSHA204_EVENT_SERIAL_NUMBER = 2
}
Functions
void bc_atsha204_init (bc_atsha204_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize ATSHA204 driver.
void bc_atsha204_set_event_handler (bc_atsha204_t *self, void(*event_handler)(bc_atsha204_t *, bc_atsha204_event_t, void *), void *event_param)
Set callback function.
bool bc_atsha204_is_ready (bc_atsha204_t *self)
Check if is ready for commands.
bool bc_atsha204_read_serial_number (bc_atsha204_t *self)
Reqeust for serial number.
bool bc_atsha204_get_serial_number (bc_atsha204_t *self, void *destination, size_t size)
Get serial number.
Detailed Description
Driver for Atmel ATSHA204 CryptoAuthentication.
Enumeration Type Documentation
enum bc_atsha204_event_t
Enumerator
BC_ATSHA204_EVENT_ERROR
Error event.
BC_ATSHA204_EVENT_REVISION_NUMBER
Event revision number is available.
BC_ATSHA204_EVENT_SERIAL_NUMBER
Event serial number is available.
Definition at line 14 of file bc_atsha204.h.
Function Documentation
bool bc_atsha204_get_serial_number (bc_atsha204_t * self, void * destination, size_t size)
Get serial number.
Parameters
[in] self Instance
[out] destination Pointer to destination object where device unique ID will be stored
[in] size Size of destination object (in bytes)
Returns
true When value is valid
false When value is invalid
Definition at line 59 of file bc_atsha204.c.
void bc_atsha204_init (bc_atsha204_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize ATSHA204 driver.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 15 of file bc_atsha204.c.
Referenced by bc_radio_init().
bool bc_atsha204_is_ready (bc_atsha204_t * self)
Check if is ready for commands.
Parameters
[in] self Instance
Returns
true If ready
false If not ready
Definition at line 35 of file bc_atsha204.c.
Referenced by bc_atsha204_get_serial_number(), and bc_atsha204_read_serial_number().
bool bc_atsha204_read_serial_number (bc_atsha204_t * self)
Reqeust for serial number.
Parameters
[in] self Instance
Returns
true On success
False When other command is in progress
Definition at line 40 of file bc_atsha204.c.
Referenced by bc_radio_init().
void bc_atsha204_set_event_handler (bc_atsha204_t * self, void(*)(bc_atsha204_t *, bc_atsha204_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 29 of file bc_atsha204.c.
Referenced by bc_radio_init().