Firmware SDK: bc_hts221
bc_hts221
Driver for HTS221 humidity sensor.
Typedefs
typedef struct bc_hts221_t bc_hts221_t
HTS221 instance.
Enumerations
enum bc_hts221_event_t {
BC_HTS221_EVENT_ERROR = 0,
BC_HTS221_EVENT_UPDATE = 1
}
Callback events.
Functions
void bc_hts221_init (bc_hts221_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize HTS221.
void bc_hts221_set_event_handler (bc_hts221_t *self, void(*event_handler)(bc_hts221_t *, bc_hts221_event_t, void *), void *event_param)
Set callback function.
void bc_hts221_set_update_interval (bc_hts221_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_hts221_measure (bc_hts221_t *self)
Start measurement manually.
bool bc_hts221_get_humidity_percentage (bc_hts221_t *self, float *percentage)
Get measured humidity as percentage.
Detailed Description
Driver for HTS221 humidity sensor.
Enumeration Type Documentation
enum bc_hts221_event_t
Callback events.
Enumerator
BC_HTS221_EVENT_ERROR
Error event.
BC_HTS221_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_hts221.h.
Function Documentation
bool bc_hts221_get_humidity_percentage (bc_hts221_t * self, float * percentage)
Get measured humidity as percentage.
Parameters
[in] self Instance
[in] percentage Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 107 of file bc_hts221.c.
Referenced by bc_tag_humidity_get_humidity_percentage().
void bc_hts221_init (bc_hts221_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize HTS221.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 53 of file bc_hts221.c.
Referenced by bc_tag_humidity_init().
bool bc_hts221_measure (bc_hts221_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 93 of file bc_hts221.c.
Referenced by bc_hts221_set_update_interval(), and bc_tag_humidity_measure().
void bc_hts221_set_event_handler (bc_hts221_t * self, void(*)(bc_hts221_t *, bc_hts221_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 71 of file bc_hts221.c.
Referenced by bc_tag_humidity_init().
void bc_hts221_set_update_interval (bc_hts221_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 77 of file bc_hts221.c.
Referenced by bc_tag_humidity_set_update_interval().