Firmware SDK: bc_hdc2080
bc_hdc2080
Driver for HDC2080 humidity sensor.
Typedefs
typedef struct bc_hdc2080_t bc_hdc2080_t
HDC2080 instance.
Enumerations
enum bc_hdc2080_event_t {
BC_HDC2080_EVENT_ERROR = 0,
BC_HDC2080_EVENT_UPDATE = 1
}
Callback events.
Functions
void bc_hdc2080_init (bc_hdc2080_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize HDC2080.
void bc_hdc2080_set_event_handler (bc_hdc2080_t *self, void(*event_handler)(bc_hdc2080_t *, bc_hdc2080_event_t, void *), void *event_param)
Set callback function.
void bc_hdc2080_set_update_interval (bc_hdc2080_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_hdc2080_measure (bc_hdc2080_t *self)
Start measurement manually.
bool bc_hdc2080_get_humidity_raw (bc_hdc2080_t *self, uint16_t *raw)
Get measured humidity as raw value.
bool bc_hdc2080_get_humidity_percentage (bc_hdc2080_t *self, float *percentage)
Get measured humidity as percentage.
bool bc_hdc2080_get_temperature_raw (bc_hdc2080_t *self, uint16_t *raw)
Get measured temperature as raw value.
bool bc_hdc2080_get_temperature_celsius (bc_hdc2080_t *self, float *celsius)
Get measured temperature in degrees of Celsius.
Detailed Description
Driver for HDC2080 humidity sensor.
Enumeration Type Documentation
enum bc_hdc2080_event_t
Callback events.
Enumerator
BC_HDC2080_EVENT_ERROR
Error event.
BC_HDC2080_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_hdc2080.h.
Function Documentation
bool bc_hdc2080_get_humidity_percentage (bc_hdc2080_t * self, float * percentage)
Get measured humidity as percentage.
Parameters
[in] self Instance
[in] percentage Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 75 of file bc_hdc2080.c.
Referenced by bc_tag_humidity_get_humidity_percentage().
bool bc_hdc2080_get_humidity_raw (bc_hdc2080_t * self, uint16_t * raw)
Get measured humidity as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 63 of file bc_hdc2080.c.
Referenced by bc_hdc2080_get_humidity_percentage(), and bc_tag_humidity_get_humidity_raw().
bool bc_hdc2080_get_temperature_celsius (bc_hdc2080_t * self, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[in] celsius Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 106 of file bc_hdc2080.c.
Referenced by bc_tag_humidity_get_temperature_celsius().
bool bc_hdc2080_get_temperature_raw (bc_hdc2080_t * self, uint16_t * raw)
Get measured temperature as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 94 of file bc_hdc2080.c.
Referenced by bc_hdc2080_get_temperature_celsius(), and bc_tag_humidity_get_temperature_raw().
void bc_hdc2080_init (bc_hdc2080_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize HDC2080.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 12 of file bc_hdc2080.c.
Referenced by bc_tag_humidity_init().
bool bc_hdc2080_measure (bc_hdc2080_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 49 of file bc_hdc2080.c.
Referenced by bc_hdc2080_set_update_interval(), and bc_tag_humidity_measure().
void bc_hdc2080_set_event_handler (bc_hdc2080_t * self, void(*)(bc_hdc2080_t *, bc_hdc2080_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 27 of file bc_hdc2080.c.
Referenced by bc_tag_humidity_init().
void bc_hdc2080_set_update_interval (bc_hdc2080_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 33 of file bc_hdc2080.c.
Referenced by bc_tag_humidity_set_update_interval().