Firmware SDK: bc_sam_m8q
bc_sam_m8q
Driver for u-blox SAM-M8Q GPS/Galileo/Glonass navigation module.
Data Structures
struct bc_sam_m8q_driver_t
SAM-M8Q driver.
struct bc_sam_m8q_time_t
Time data structure.
struct bc_sam_m8q_position_t
Position data structure.
struct bc_sam_m8q_altitude_t
Altitude data structure.
struct bc_sam_m8q_quality_t
Quality data structure.
struct bc_sam_m8q_accuracy_t
Accuracy data structure.
Typedefs
typedef struct bc_sam_m8q_t bc_sam_m8q_t
SAM-M8Q instance.
Enumerations
enum bc_sam_m8q_event_t {
BC_SAM_M8Q_EVENT_ERROR = 0,
BC_SAM_M8Q_EVENT_START = 1,
BC_SAM_M8Q_EVENT_UPDATE = 2,
BC_SAM_M8Q_EVENT_STOP = 3
}
Callback events.
Functions
void bc_sam_m8q_init (bc_sam_m8q_t *self, bc_i2c_channel_t channel, uint8_t i2c_address, const bc_sam_m8q_driver_t *driver)
Initialize SAM-M8Q module driver.
void bc_sam_m8q_set_event_handler (bc_sam_m8q_t *self, bc_sam_m8q_event_handler_t event_handler, void *event_param)
Set callback function.
void bc_sam_m8q_start (bc_sam_m8q_t *self)
Start navigation module.
void bc_sam_m8q_stop (bc_sam_m8q_t *self)
Stop navigation module.
void bc_sam_m8q_invalidate (bc_sam_m8q_t *self)
Invalidate navigation data.
bool bc_sam_m8q_get_time (bc_sam_m8q_t *self, bc_sam_m8q_time_t *time)
Get time.
bool bc_sam_m8q_get_position (bc_sam_m8q_t *self, bc_sam_m8q_position_t *position)
Get position.
bool bc_sam_m8q_get_altitude (bc_sam_m8q_t *self, bc_sam_m8q_altitude_t *altitude)
Get altitude.
bool bc_sam_m8q_get_quality (bc_sam_m8q_t *self, bc_sam_m8q_quality_t *quality)
Get quality.
bool bc_sam_m8q_get_accuracy (bc_sam_m8q_t *self, bc_sam_m8q_accuracy_t *accuracy)
Get accuracy.
Variables
bool(* bc_sam_m8q_driver_t::on)(bc_sam_m8q_t *self)
Callback for power on.
bool(* bc_sam_m8q_driver_t::off)(bc_sam_m8q_t *self)
Callback for power off.
int bc_sam_m8q_time_t::year
Year.
int bc_sam_m8q_time_t::month
Month.
int bc_sam_m8q_time_t::day
Day.
int bc_sam_m8q_time_t::hours
Hours.
int bc_sam_m8q_time_t::minutes
Minutes.
int bc_sam_m8q_time_t::seconds
Seconds.
float bc_sam_m8q_position_t::latitude
Latitude.
float bc_sam_m8q_position_t::longitude
Longitude.
float bc_sam_m8q_altitude_t::altitude
Altitude.
char bc_sam_m8q_altitude_t::units
Units of altitude.
int bc_sam_m8q_quality_t::fix_quality
Fix quality.
int bc_sam_m8q_quality_t::satellites_tracked
Number of satellites tracked.
float bc_sam_m8q_accuracy_t::horizontal
Horizontal accuracy estimate.
float bc_sam_m8q_accuracy_t::vertical
Vertical accuracy estimate.
Detailed Description
Driver for u-blox SAM-M8Q GPS/Galileo/Glonass navigation module.
Enumeration Type Documentation
enum bc_sam_m8q_event_t
Callback events.
Enumerator
BC_SAM_M8Q_EVENT_ERROR
Error event.
BC_SAM_M8Q_EVENT_START
Start event.
BC_SAM_M8Q_EVENT_UPDATE
Update event.
BC_SAM_M8Q_EVENT_STOP
Stop event.
Definition at line 13 of file bc_sam_m8q.h.
Function Documentation
bool bc_sam_m8q_get_accuracy (bc_sam_m8q_t * self, bc_sam_m8q_accuracy_t * accuracy)
Get accuracy.
Parameters
[in] self Instance
[out] accuracy Accuracy data structure
Returns
true On success
false On failure
Definition at line 124 of file bc_sam_m8q.c.
Referenced by bc_module_gps_get_accuracy().
bool bc_sam_m8q_get_altitude (bc_sam_m8q_t * self, bc_sam_m8q_altitude_t * altitude)
Get altitude.
Parameters
[in] self Instance
[out] altitude Altitude data structure
Returns
true On success
false On failure
Definition at line 94 of file bc_sam_m8q.c.
Referenced by bc_module_gps_get_altitude().
bool bc_sam_m8q_get_position (bc_sam_m8q_t * self, bc_sam_m8q_position_t * position)
Get position.
Parameters
[in] self Instance
[out] position Position data structure
Returns
true On success
false On failure
Definition at line 79 of file bc_sam_m8q.c.
Referenced by bc_module_gps_get_position().
bool bc_sam_m8q_get_quality (bc_sam_m8q_t * self, bc_sam_m8q_quality_t * quality)
Get quality.
Parameters
[in] self Instance
[out] quality Quality data structure
Returns
true On success
false On failure
Definition at line 109 of file bc_sam_m8q.c.
Referenced by bc_module_gps_get_quality().
bool bc_sam_m8q_get_time (bc_sam_m8q_t * self, bc_sam_m8q_time_t * time)
Get time.
Parameters
[in] self Instance
[out] time Time data structure
Returns
true On success
false On failure
Definition at line 60 of file bc_sam_m8q.c.
Referenced by bc_module_gps_get_time().
void bc_sam_m8q_init (bc_sam_m8q_t * self, bc_i2c_channel_t channel, uint8_t i2c_address, const bc_sam_m8q_driver_t * driver)
Initialize SAM-M8Q module driver.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
[in] driver Optional driver (can be NULL)
Definition at line 13 of file bc_sam_m8q.c.
Referenced by bc_module_gps_init().
void bc_sam_m8q_set_event_handler (bc_sam_m8q_t * self, bc_sam_m8q_event_handler_t event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 26 of file bc_sam_m8q.c.
Referenced by bc_module_gps_init().
void bc_sam_m8q_start (bc_sam_m8q_t * self)
Start navigation module.
Parameters
[in] self Instance
Definition at line 32 of file bc_sam_m8q.c.
Referenced by bc_module_gps_start().
void bc_sam_m8q_stop (bc_sam_m8q_t * self)
Stop navigation module.
Parameters
[in] self Instance
Definition at line 43 of file bc_sam_m8q.c.
Referenced by bc_module_gps_stop().