Firmware SDK: bc_tmp112
bc_tmp112
Driver for TMP112 temperature sensor.
Typedefs
typedef struct bc_tmp112_t bc_tmp112_t
TMP112 instance.
Enumerations
enum bc_tmp112_event_t {
BC_TMP112_EVENT_ERROR = 0,
BC_TMP112_EVENT_UPDATE = 1
}
Callback events.
Functions
void bc_tmp112_init (bc_tmp112_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize TMP112.
void bc_tmp112_deinit (bc_tmp112_t *self)
Deinitialize TMP112.
void bc_tmp112_set_event_handler (bc_tmp112_t *self, void(*event_handler)(bc_tmp112_t *, bc_tmp112_event_t, void *), void *event_param)
Set callback function.
void bc_tmp112_set_update_interval (bc_tmp112_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_tmp112_measure (bc_tmp112_t *self)
Start measurement manually.
bool bc_tmp112_get_temperature_raw (bc_tmp112_t *self, int16_t *raw)
Get measured temperature as raw value.
bool bc_tmp112_get_temperature_celsius (bc_tmp112_t *self, float *celsius)
Get measured temperature in degrees of Celsius.
bool bc_tmp112_get_temperature_fahrenheit (bc_tmp112_t *self, float *fahrenheit)
Get measured temperature in degrees of Fahrenheit.
bool bc_tmp112_get_temperature_kelvin (bc_tmp112_t *self, float *kelvin)
Get measured temperature in kelvin.
Detailed Description
Driver for TMP112 temperature sensor.
Enumeration Type Documentation
enum bc_tmp112_event_t
Callback events.
Enumerator
BC_TMP112_EVENT_ERROR
Error event.
BC_TMP112_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_tmp112.h.
Function Documentation
void bc_tmp112_deinit (bc_tmp112_t * self)
Deinitialize TMP112.
Parameters
[in] self Instance
Definition at line 26 of file bc_tmp112.c.
bool bc_tmp112_get_temperature_celsius (bc_tmp112_t * self, float * celsius)
Get measured temperature in degrees of Celsius.
Parameters
[in] self Instance
[out] celsius Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 83 of file bc_tmp112.c.
Referenced by bc_module_climate_get_temperature_celsius(), bc_tag_temperature_get_temperature_celsius(), bc_tmp112_get_temperature_fahrenheit(), and bc_tmp112_get_temperature_kelvin().
bool bc_tmp112_get_temperature_fahrenheit (bc_tmp112_t * self, float * fahrenheit)
Get measured temperature in degrees of Fahrenheit.
Parameters
[in] self Instance
[out] fahrenheit Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 97 of file bc_tmp112.c.
Referenced by bc_module_climate_get_temperature_fahrenheit(), and bc_tag_temperature_get_temperature_fahrenheit().
bool bc_tmp112_get_temperature_kelvin (bc_tmp112_t * self, float * kelvin)
Get measured temperature in kelvin.
Parameters
[in] self Instance
[out] kelvin Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 111 of file bc_tmp112.c.
Referenced by bc_module_climate_get_temperature_kelvin(), and bc_tag_temperature_get_temperature_kelvin().
bool bc_tmp112_get_temperature_raw (bc_tmp112_t * self, int16_t * raw)
Get measured temperature as raw value.
Parameters
[in] self Instance
[out] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 71 of file bc_tmp112.c.
Referenced by bc_tag_temperature_get_temperature_raw(), and bc_tmp112_get_temperature_celsius().
void bc_tmp112_init (bc_tmp112_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize TMP112.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 11 of file bc_tmp112.c.
Referenced by bc_module_climate_init(), and bc_tag_temperature_init().
bool bc_tmp112_measure (bc_tmp112_t * self)
Start measurement manually.
Parameters
[in] self Instance
Returns
true On success
false When other measurement is in progress
Definition at line 57 of file bc_tmp112.c.
Referenced by bc_module_climate_measure_all_sensors(), bc_module_climate_measure_thermometer(), bc_tag_temperature_measure(), and bc_tmp112_set_update_interval().
void bc_tmp112_set_event_handler (bc_tmp112_t * self, void(*)(bc_tmp112_t *, bc_tmp112_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 35 of file bc_tmp112.c.
Referenced by bc_module_climate_init(), and bc_tag_temperature_set_event_handler().
void bc_tmp112_set_update_interval (bc_tmp112_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 41 of file bc_tmp112.c.
Referenced by bc_module_climate_set_update_interval_all_sensors(), bc_module_climate_set_update_interval_thermometer(), and bc_tag_temperature_set_update_interval().