Firmware SDK: bc_tick
bc_tick
Timestamp functions.
Macros
#define BC_TICK_INFINITY UINT64_C(0xffffffffffffffff)
Maximum timestamp value.
Typedefs
typedef uint64_t bc_tick_t
Timestamp data type.
Functions
bc_tick_t bc_tick_get (void)
Get absolute timestamp since start of program.
void bc_tick_wait (bc_tick_t delay)
Delay execution for specified amount of ticks.
void bc_tick_inrement_irq (bc_tick_t delta)
Detailed Description
Timestamp functions.
Function Documentation
bc_tick_t bc_tick_get (void)
Get absolute timestamp since start of program.
Returns
Timestamp in milliseconds
Definition at line 7 of file bc_tick.c.
Referenced by bc_aes_key_derivation(), bc_cy8cmbr3102_set_scan_interval(), bc_i2c_init(), bc_lp8_init(), bc_module_lcd_draw_image(), bc_ramp_get(), bc_ramp_start(), bc_sc16is740_read(), bc_scheduler_plan_current_from_now(), bc_scheduler_plan_from_now(), bc_scheduler_run(), bc_spirit1_set_rx_timeout(), bc_sps30_measure(), bc_tick_wait(), and bc_uart_read().
void bc_tick_wait (bc_tick_t delay)
Delay execution for specified amount of ticks.
Parameters
[in] delay Number of ticks to wait
Definition at line 23 of file bc_tick.c.