Firmware SDK: bc_fifo
bc_fifo
FIFO buffer implementation.
Data Structures
struct bc_fifo_t
Structure of FIFO instance.
Functions
void bc_fifo_init (bc_fifo_t *fifo, void *buffer, size_t size)
Initialize FIFO buffer.
void bc_fifo_purge (bc_fifo_t *fifo)
Purge FIFO buffer.
size_t bc_fifo_write (bc_fifo_t *fifo, const void *buffer, size_t length)
Write data to FIFO.
size_t bc_fifo_read (bc_fifo_t *fifo, void *buffer, size_t length)
Read data from FIFO.
size_t bc_fifo_irq_write (bc_fifo_t *fifo, const void *buffer, size_t length)
Write data to FIFO from interrupt.
size_t bc_fifo_irq_read (bc_fifo_t *fifo, void *buffer, size_t length)
Read data from FIFO from interrupt.
bool bc_fifo_is_empty (bc_fifo_t *fifo)
Is empty.
Detailed Description
FIFO buffer implementation.
Function Documentation
void bc_fifo_init (bc_fifo_t * fifo, void * buffer, size_t size)
Initialize FIFO buffer.
Parameters
[in] fifo FIFO instance
[in] buffer Pointer to buffer where FIFO holds data
[in] size Size of buffer where FIFO holds data
Definition at line 4 of file bc_fifo.c.
Referenced by bc_atci_init(), bc_cmwx1zzabz_init(), bc_dma_init(), bc_esp8266_init(), bc_td1207r_init(), bc_usb_cdc_init(), and bc_wssfm10r1at_init().
size_t bc_fifo_irq_read (bc_fifo_t * fifo, void * buffer, size_t length)
Read data from FIFO from interrupt.
Parameters
[in] fifo FIFO instance
[out] buffer Pointer to buffer where data will be read
[in] length Number of requested bytes to be read
Returns
Number of bytes read
Definition at line 133 of file bc_fifo.c.
size_t bc_fifo_irq_write (bc_fifo_t * fifo, const void * buffer, size_t length)
Write data to FIFO from interrupt.
Parameters
[in] fifo FIFO instance
[in] buffer Pointer to buffer from which data will be written
[in] length Number of requested bytes to be written
Returns
Number of bytes written
Definition at line 101 of file bc_fifo.c.
bool bc_fifo_is_empty (bc_fifo_t * fifo)
Is empty.
Parameters
[in] fifo FIFO instance
Returns
true When is empty
false When is not empty
Definition at line 161 of file bc_fifo.c.
void bc_fifo_purge (bc_fifo_t * fifo)
Purge FIFO buffer.
Parameters
[in] fifo FIFO instance
Definition at line 12 of file bc_fifo.c.
size_t bc_fifo_read (bc_fifo_t * fifo, void * buffer, size_t length)
Read data from FIFO.
Parameters
[in] fifo FIFO instance
[out] buffer Pointer to buffer where data will be read
[in] length Number of requested bytes to be read
Returns
Number of bytes read
Definition at line 63 of file bc_fifo.c.
Referenced by bc_module_rs485_async_read(), bc_uart_async_read(), and bc_usb_cdc_read().
size_t bc_fifo_write (bc_fifo_t * fifo, const void * buffer, size_t length)
Write data to FIFO.
Parameters
[in] fifo FIFO instance
[in] buffer Pointer to buffer from which data will be written
[in] length Number of requested bytes to be written
Returns
Number of bytes written
Definition at line 18 of file bc_fifo.c.
Referenced by bc_module_rs485_async_write(), and bc_uart_async_write().